apiVersion: v1
kind: Service
metadata:
  name: backend-feed-deployment
  labels:
    run: backend-feed-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: backend-feed-deployment