apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-reverseproxy
  labels:
    app: my-app-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-reverseproxy
  template:
    metadata:
      labels:
        app: my-app-reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: fadyfawzy/reverseproxy
        ports:
        - containerPort: 80