apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  credentials:  YXdzX2FjY2Vzc19rZXlfaWQgPUFLSUFYQlg2Q0QzU0pON1hZNTJPCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9RTFFSW1GRmRVRlBCTnJtZjdRTGFjOEtPeVRVU29qK2xOL3E3Zm9qOAo=
type: Opaque


  