apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-front
  labels:
    app: my-app-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-front
  template:
    metadata:
      labels:
        app: my-app-front
    spec:
      containers:
      - name: udagram-frontend
        image: fadyfawzy/udagram-frontend
        ports:
        - containerPort: 80