apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-front
  labels:
    app: my-app-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-front
  template:
    metadata:
      labels:
        app: my-app-front
    spec:
      containers:
      - name: udagram-frontend
        image: fadyfawzy/udagram-frontend
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80