apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user-deployment
  template:
    metadata:
      labels:
        app: backend-user-deployment
    spec:
      containers:
      - name: udagram-api-user
        image: fadyfawzy/udagram-api-user
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 15
