apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-user
  labels:
    app: my-app-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-user
  template:
    metadata:
      labels:
        app: my-app-user
    spec:
      containers:
      - name: udagram-api-user
        image: fadyfawzy/udagram-api-user
        ports:
        - containerPort: 80